---
##
# Copyright OpenSearch Contributors
# SPDX-License-Identifier: Apache-2.0
##

codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 70%    # the required coverage value
        threshold: 1%  # the leniency in hitting the target
