name: Test and Build OpenSearch Observability Backend Plugin on Java 8

on: [push, pull_request]

env:
  OPENSEARCH_VERSION: '1.3.0-SNAPSHOT'
  OPENSEARCH_BRANCH: '1.3'
  COMMON_UTILS_BRANCH: 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Gradle 
        run: |
          cd opensearch-observability
          ./gradlew build -Dopensearch.version=${{ env.OPENSEARCH_VERSION }} --build-cache

      - name: Set up JDK 1.08
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 8
        
      - name: Test with Java 8
        run: |
          cd opensearch-observability
          ./gradlew test -Dopensearch.version=${{ env.OPENSEARCH_VERSION }} --build-cache
