name: Test OpenSearch Observability on Java 8

on: [push, pull_request]

env:
  OPENSEARCH_VERSION: '1.3.0-SNAPSHOT'

 jobs:
  build:
    name: Test on Java 8
    runs-on: ubuntu-latest
  
    steps:
      - name: Set up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: Checkout OpenSearch Observability
        uses: actions/checkout@v2

      - name: Build with Java 11
        run: |
          cd opensearch-observability
          ./gradlew build -Dopensearch.version=${{ env.OPENSEARCH_VERSION }}

      - name: Set up Java 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Test with Java 8
        run: |
          cd opensearch-observability
          ./gradlew test -Dopensearch.version=${{ env.OPENSEARCH_VERSION }} 
